### ISSUE TITLE
Unification doesn't return solutions for all type inference variables

### ISSUE THREAD

**Issue by RaefM** [fplab/type-inference-paper#4]
Not all holes are given a solution under the current unification results. To see an example of this, note test case 6 (copied below) or any test case that is only a hole (like 0 below).

======[0]======
EXP:   let x = (|[0]|) in x
CONTEXT:

+ syn/ana result typ:
 THole[0]

+ constraints:

+ unify results: (<hole_id>) (<type>)

======[6]======
EXP:   λx:THole[2].x x + 5
CONTEXT:

+ syn/ana result typ:
 THole[2]->THole[4]

+ constraints:
THole[2] == THole[3]->THole[4]
TNum == THole[2]
TNum == TNum
THole[3] == TNum

+ unify results: (<hole_id>) (<type>)
solved: (3) (TNum)
unsolved: (2) (TNum, TNum->THole[4],  )
=============

Before discussing the issue, it is also of note that precedence doesn't seem to be applied correctly in case [6]; space should be applied before plus resulting in THole[2] needing to be consistent with both THole[3] -> THole[4] and THole[3] where THole[4] must be consistent with TNum. This smaller issue (which can be solved by just writing test cases in structural syntax since this wouldn't be an issue in Hazel) will be ignored in discussion of the subject issue.

In case [0] above, THole[0] is given no unifcation result. The same occurs in case [6] for THole[4]. This is likely since there are no constraints these variables are dependent upon (THole[2] = THole[3] -> THole[4] could be argued to constrain THole[4] to be unsolved as well since TNum, one equivalence, has no matched arrow type, but this consideration is the goal of top-sort and would require information on THole[4] be passed down; as such, we would need to know the solution status of THole[4] in order to solve it which, as the subject line states, is not currently returned).

**Comment by RaefM** [comment]
All type variables described are unbound in their solutions (at least as far as the unify function should be able to tell before top-sort). A simple solution for at least these two cases might be to make the initial constraint set contain constraints that equate all holes to themselves. Another solution may be to add an Unbound unify_result status (alongside Solved and Unsolved)?

**Comment by cyrus-** [comment]
if there aren't any solutions then we can just leave it as an empty hole (later we can think about when it would be appropriate to generalize to a forall)

**Comment by RaefM** [comment]
This has implicity been fixed with recent dfs changes- any referenced hole is added as a reference as it may gain more information or act as a vital link in dfs.
